# Generated by Django 4.2.13 on 2024-11-13 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('article_type', models.CharField(max_length=180)),
                ('chapter', models.CharField(max_length=180, null=True)),
                ('duration', models.CharField(max_length=180, null=True)),
                ('thumbnail', models.ImageField(blank=True, default='/img/blank.png', null=True, upload_to='img')),
                ('tags', models.TextField(null=True)),
                ('article_content', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiApp.department')),
            ],
        ),
    ]
