# Generated by Django 5.1.3 on 2024-12-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='title',
            field=models.CharField(max_length=180, unique=True),
        ),
    ]
