# Generated by Django 4.2.13 on 2024-11-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_alter_article_chapter_alter_article_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default='/img/blank.png', upload_to='img'),
        ),
    ]
