# Generated by Django 4.2.13 on 2024-11-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0005_department_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=180)),
                ('answer', models.CharField(max_length=180)),
                ('related_article', models.CharField(max_length=180)),
            ],
        ),
    ]
