# Generated by Django 4.2.13 on 2024-11-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0006_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='related_article',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
